### ISSUE TITLE
Chatwidget  error after install agenda module

### ISSUE THREAD

**Issue by PaulBartelings** [LJPc-solutions/freescout-calendar-module#57] opened 2024-10-24 09:09 UTC
Hi there,
foremost, thanks for the nice module, I love it.

I have one issue and that is after I installed your module I get this error message on my website if I use my chat widget.

**messages.error_occured**

Can you please give me advice on how to fix this?

Thanks in advance 
Paul

**Comment by PaulBartelings** [comment] 2024-10-24 09:14
![chatwidget](https://github.com/user-attachments/assets/982cbd35-f643-4254-b461-97cd943a7350)

**Comment by Lars-** [comment] 2024-10-24 14:46
Hi Paul,

It probably is some filter in the service provider that is causing the problem, but I have no clue what it could be exactly. Since I don’t have access to the chat module I unfortunately can’t check it myself. If you have any idea what causes it, please feel free to submit a pull request.

**Comment by PaulBartelings** [comment] 2024-10-25 19:45
Hi Lars, the problem occurs on several websites I have tried on. Different providers. It also occurs on several other official modules of freescout. End user portal, knowledge base and the chat module. These all stop working as soon as the calendar is activated. Even when I test the chat widget within freescount I get the error message. I would be happy to gift you a license code for the chat module for free if that will help you solve this problem.

Greets Paul

**Comment by Lars-** [comment] 2024-10-26 14:49
Thank you for the update. I will see what I can do next week. If I need the license, I’ll let you know.

**Comment by Lars-** [comment] 2024-10-28 13:42
What version of freescout are you using on what PHP version? I could reproduce the problems on an old freescout version, but not on the newest.

**Comment by PaulBartelings** [comment] 2024-10-28 16:40
Hi Lars,

I hope the latest version. ![image](https://github.com/user-attachments/assets/eef456b2-a31e-4000-9327-4716eaa2b9fe)

**Comment by Lars-** [comment] 2024-10-28 16:42
That is indeed the latest version. Is it possible for you to test if this still occurs on php8.3?

**Comment by PaulBartelings** [comment] 2024-10-28 16:59
Sure ill let you know 😏

**Comment by PaulBartelings** [comment] 2024-10-28 17:14
Problem is still there. ![image](https://github.com/user-attachments/assets/d9835d22-e9b3-4123-92b0-69bc7ced1545)

**Comment by Lars-** [comment] 2024-10-29 10:16
I can reproduce the problem, but it does not dissapear when I disable the calendar module. When sending a message via the chat, an ajax endpoint is called, can you send the payload? For example, this is mine:
![image](https://github.com/user-attachments/assets/c7262a51-da1f-4636-961e-d98250461993)

It fails at my end because conversation_id is "null", but that doesn't change when I disable the calendar module.

**Comment by PaulBartelings** [comment] 2024-10-29 13:01
Clear browser history and start a new conversation,
This is what I get, 

![chat 1](https://github.com/user-attachments/assets/b67daae3-97f7-41c0-83f8-aa2a3ccd4fd8)

After I turn off your module and submit the form and one message, this is what I get,

![CleanShot 2024-10-29 at 13 45 59](https://github.com/user-attachments/assets/c6295dac-e574-4a76-bf8e-f7b6b6538240)

And if I turn on your module, everything works fine for me, but not for a new visitor. 
When I clear my browser history and try again, I have the same issue.  

Look like a cookie thing

**Comment by Lars-** [comment] 2024-10-29 15:25
But now you are doing a different thing: updating your information.
Can you test with the actual submit action (by submitting a message)? The customer_id is set after you've entered your info.

**Comment by PaulBartelings** [comment] 2024-10-29 19:17
Hi Lars,

This is the first message output,

![CleanShot 2024-10-29 at 20 15 35](https://github.com/user-attachments/assets/353ded77-3673-473d-add1-53f8b0f30302)

**Comment by PaulBartelings** [comment] 2024-11-05 15:00
Hi Lars,
Do you need something else from me?

**Comment by Lars-** [comment] 2024-11-05 15:49
No, I think I have enough information to fix it. It's unfortunately too busy at the moment to actually fix it. I will do my best to get back to you as soon as possible.

**Comment by Lars-** [comment] 2024-11-07 15:15
[This line](https://github.com/LJPc-solutions/freescout-calendar-module/blob/9f438703622c651a7871624269c95cf0e3650b1a/Providers/LJPcCalendarModuleServiceProvider.php#L34C7-L34C33) causes the issue. I'm trying to fix it.

**Comment by Lars-** [comment] 2024-11-07 15:32
Fixed in 2.1.3!

 The package `sabre/dav` includes `psr/log` v1, v2 or v3 (so v3 by default). Freescout uses v1, so this caused the issue.

**Closed as completed by Lars-** 2024-11-07 15:32 UTC

**Comment by PaulBartelings** [comment] 2024-11-08 19:15
Wauw, thanks did the update, and it works fine now.

Good job :)
