### ISSUE TITLE
Daylight Savings Bug

### ISSUE THREAD

**Issue by JinksKid** [LJPc-solutions/freescout-calendar-module#21] opened 2023-01-26 01:58 UTC
Hello,

When creating a new item, Its putting it the database an hour before the time i specified.
Ie. I set an item for 12pm, and after a few seconds it changes it to 11am.
So when creating an all day item, it gets placed on the day before.
I assume this is due to daylight savings?
My timezone is Sydney GMT +10  but with daylight savings its technically +11

**Comment by Lars-** [comment] 2023-01-26 06:49
I had the same problem when I built the module. I think the solution was to set the timezone in the freescout .env file. What timezone do you have set there?

**Comment by JinksKid** [comment] 2023-01-26 07:20
Its currenlty set to Australia/Sydney
I just tried to change it to a GMT +11 zone.. but now all my emails are an hour out.
Have also commented app_timezone out so it uses php.ini instead.. but same issue as before.

**Comment by JinksKid** [comment] 2023-01-26 07:36
Some local debugging

echo date('d-m-y h:i:s');   shows 7:30pm  incorrect

date_default_timezone_set('Australia/Sydney');  
echo date('d-m-y h:i:s');  shows 6:30pm   correct

timezone is set in php.ini as Australia/Sydney aswell as in freescout settings.

**Comment by Lars-** [comment] 2023-01-26 08:29
Ah, there is another place where you can set your timezone. It's in your profile (right click your name in freescout and then click on My Account). 
Please check if changing the timezone there fixes it.

**Comment by JinksKid** [comment] 2023-01-26 08:46
It was set to Melbourne/Sydney +10
changed to to +11 and created a new item. Same Thing, a few seconds after its added it goes back by an hour. :(

**Comment by Lars-** [comment] 2023-01-27 07:25
Okay, then it's probably the same reason why `echo date('d-m-y h:i:s');`  returns the wrong time.
What happens if you add `date_default_timezone_set('Australia/Sydney'); ` to the first line of the `createItem` function in LJPcCalendarModuleController.php? This is of course not a solution, but a debug attempt.

**Comment by JinksKid** [comment] 2023-01-27 09:44
Yep. that seems to work.

**Comment by Lars-** [comment] 2023-01-27 20:53
Okay, cool. I don't have much time the next couple of days. Can you make a pull request where you simply use the date_default_timezone_set function in the createItem function with the app timezone in it? I think it should be fixed then.

**Comment by JinksKid** [comment] 2023-01-28 01:13
I think my testing was insufficient.
Without adding date_default_timezone_set  seems to work fine when creating an item within the current daylight savings period.
If i create an item in july, well after daylight savings ends, thats when it goes an hour out. 
It does this with or without date_default_timezone_set.

**Comment by Lars-** [comment] 2023-01-28 11:42
Hmmm... And how does that work when you do that in php, so what does date('d-m-y h:i:s', strtotime('2023-07-01')) do?

**Comment by JinksKid** [comment] 2023-01-29 14:09
Sorry for the late reply. Here are the results

echo date('d-m-y h:i:s', strtotime('2023-07-01'));                         01-07-23 12:00:00
echo date('d-m-y h:i:s', strtotime('2023-07-01 2:00:00'));            01-07-23 02:00:00

**Comment by ramboramage** [comment] 2023-05-24 10:55
Hi Lars, me again...
I'm now having this issue also. I suspect it's because the shared hosting server we are using has a time zone 1 hour behind our own (Europe/London). I've confirmed the time zone in freescout and changed the time zone in PHP with no change.
I checked the .env file also and that is correct.
I don't recall seeing the issue yesterday however the hosting server could have changed.
Not sure if there may be a 'fudge' to get it working correctly? unfortunately I don't have control of the server time zone.

**Comment by Lars-** [comment] 2023-05-24 13:59
Hi! Can you try to change the CalendarItem entity file to this?

```php
<?php

namespace Modules\LJPcCalendarModule\Entities;

use App\User;
use DateTime;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use JsonSerializable;

/**
 * @property int $id
 * @property int $calendar_id
 * @property int $author_id
 * @property bool $is_all_day
 * @property bool $is_private
 * @property bool $is_read_only
 * @property string $title
 * @property string $body
 * @property string $state
 * @property string $location
 * @property DateTime $start
 * @property DateTime $end
 */
class CalendarItem extends Model implements JsonSerializable {
		public const ACTION_TYPE_ADD_TO_CALENDAR = 186;

		protected $table = 'calendar_items';
		protected $fillable = [
				'calendar_id',
				'author_id',
				'is_all_day',
				'is_private',
				'is_read_only',
				'title',
				'body',
				'state',
				'location',
				'start',
				'end',
		];

		protected $casts = [
				'start' => 'datetime',
				'end'   => 'datetime',
		];

		public function calendar(): BelongsTo {
				return $this->belongsTo( Calendar::class );
		}

		public function jsonSerialize(): array {
				$retArr = [
						'id'         => $this->id,
						'title'      => $this->title,
						'location'   => $this->location,
						'body'       => $this->body,
						'state'      => $this->state,
						'start'      => $this->start->setTimezone( config( 'app.timezone' ) )->format( 'Y-m-d H:i:s' ),
						'end'        => $this->end->setTimezone( config( 'app.timezone' ) )->format( 'Y-m-d H:i:s' ),
						'isAllDay'   => (int) $this->is_all_day,
						'category'   => $this->is_all_day ? 'allday' : 'time',
						'isPrivate'  => (int) $this->is_private,
						'isReadOnly' => (int) $this->is_read_only,
						'calendarId' => (int) $this->calendar_id,
						'raw'        => [],
				];

				$creator = User::where( 'id', $this->author_id )->first();
				if ( $creator !== null ) {
						$retArr['raw']['creator'] = [
								'id'     => $this->author_id,
								'name'   => $creator->getFullName(),
								'email'  => $creator->email,
								'avatar' => $creator->getPhotoUrl(),
								'phone'  => $creator->phone,
						];
				}

				return $retArr;
		}
}
```

**Comment by ramboramage** [comment] 2023-05-24 14:35
Hi Lars,
I can confirm that has fixed the issue for me.
Legend.
Many thanks,
Stuart.

**Closed** 2023-05-24 14:44 UTC
